version: '2'

services:

  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./registry/conf:/etc/docker/registry:ro"
      - "./registry/data:/var/lib/registry:rw"
    networks:
      - registry-net

  registry-manager:
    image: snagles/docker-registry-manager
    restart: always
    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
    ports:
      - "8080:8080"
    networks:
      - registry-net
    depends_on:
      - registry
    volumes:
      - ./registry-manager/registries.yml:/app/registries.yml

networks:
  registry-net:
      driver: bridge
