version: '2'

services:

  registry:
    image: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./registry/conf:/etc/docker/registry:ro"
      - "./registry/data:/var/lib/registry:rw"
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  registry-manager:
    image: snagles/docker-registry-manager:v3.0.0
    restart: always
    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
    ports:
      - "8080:8080"
    networks:
      - registry-net
    depends_on:
      - registry
    volumes:
      - ./registry-manager/registries.yml:/app/registries.yml

networks:
  registry-net:
      driver: bridge
